### ISSUE TITLE
Add completion

### ISSUE THREAD

**Issue by jcubic** [4s3ti/legacy-terminalCV#1]
Just found that you had this terminal while looking at notifications on GitHub.

There is one feature that you may want to use, when you type part of the word and press TAB it will complete the word if it's unique and if not you need to type twice to show list of commands.

The only documentation right now is [API reference](https://terminal.jcubic.pl/api_reference.php#completion) I need to add more docs to Wiki with examples like Getting Started guide.

it basic function add option:
```
   completion: ['help', 'whois', 'about', 'social'] // add rest of the commands
```

this is basic usage, you can also use function where you can return Array or Promise of Array.

**Comment by 4s3ti** [comment]
Cool thanks a lot! will look into adding it as soon as i have a bit of time :D

**Comment by 4s3ti** [comment]
Well 2 years later ... i got a "bit" ... this repo going to be archived, moved this template to a hugo template where this was implemented: https://github.com/4s3ti/terminalcv 

Thanks a lot! :D
